import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Providers } from "./GlobalRedux/provider";
import Home from "./elements/Home";
const inter = Inter({ subsets: ["latin"] });
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
      <Providers>
       <div className="z-2">
       <Home/> 
       </div>
        {children}
        </Providers>
        </body>
    </html>
    </ClerkProvider>
    
  );
}